name: aimi_lib
description: A Dart library for interacting with anime APIs and playing videos.
version: 1.1.0
repository: https://github.com/brokiem/aimi-lib

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.6.0
  html: ^0.15.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
